parameters:
#    siphoc_pdf.example.class: Siphoc\PdfBundle\Example

services:
    tijsverkoyen.css_to_inline:
        class: TijsVerkoyen\CssToInlineStyles\CssToInlineStyles

    buzz.request:
        class: Buzz\Message\Request

    buzz.response:
        class: Buzz\Message\Response

    buzz.client:
        class: Buzz\Client\FileGetContents

    knp.snappy.pdf:
        class: Knp\Snappy\Pdf
        arguments: [ '/usr/local/bin/wkhtmltopdf' ]

    siphoc.buzz_request_handler:
        class: Siphoc\PdfBundle\Util\BuzzRequestHandler
        arguments: [ @buzz.request, @buzz.response, @buzz.client ]

    siphoc.pdf.css_to_inline:
        class: Siphoc\PdfBundle\Util\CssToInline
        arguments: [ @tijsverkoyen.css_to_inline, @siphoc.buzz_request_handler ]

    siphoc.pdf.js_to_html:
        class: Siphoc\PdfBundle\Util\JSToHTML
        arguments: [ @siphoc.buzz_request_handler ]

    siphoc.pdf.generator:
        class: Siphoc\PdfBundle\Util\PdfGenerator
        arguments: [ @siphoc.pdf.css_to_inline, @siphoc.pdf.js_to_html, @knp.snappy.pdf ]

