parameters:
    siphoc_pdf.basepath: ~
    siphoc_pdf.options: []
    siphoc_pdf.binary: '/usr/local/bin/wkhtmltopdf'

services:
    buzz.request:
        class: Buzz\Message\Request

    buzz.response:
        class: Buzz\Message\Response

    buzz.client:
        class: Buzz\Client\FileGetContents

    knp.snappy.pdf:
        class: Knp\Snappy\Pdf
        arguments: [ %siphoc_pdf.binary%, %siphoc_pdf.options% ]

    siphoc.buzz_request_handler:
        class: Siphoc\PdfBundle\Util\BuzzRequestHandler
        arguments: [ @buzz.request, @buzz.response, @buzz.client ]

    siphoc.pdf.css_to_html:
        class: Siphoc\PdfBundle\Converter\CssToHTML
        arguments: [ @siphoc.buzz_request_handler ]
        calls:
            - [ setBasePath, [ %siphoc_pdf.basepath% ] ]

    siphoc.pdf.js_to_html:
        class: Siphoc\PdfBundle\Converter\JSToHTML
        arguments: [ @siphoc.buzz_request_handler ]
        calls:
            - [ setBasePath, [ %siphoc_pdf.basepath% ] ]

    siphoc.pdf.generator:
        class: Siphoc\PdfBundle\Generator\PdfGenerator
        arguments: [ @siphoc.pdf.css_to_html, @siphoc.pdf.js_to_html, @knp.snappy.pdf ]
